"""empty message

Revision ID: 275728dcc58e
Revises: 4f30cae1934e
Create Date: 2021-05-06 12:43:41.267202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275728dcc58e'
down_revision = '4f30cae1934e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profileImage', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profileImage')
    # ### end Alembic commands ###
